### ISSUE TITLE
A question about cocoa

### ISSUE THREAD

**Issue by codlife** [gingsmith/cocoa#1]
Hi @gingsmith 
 I'm very sorry to ask you this question. I have seen your code, mini-batch SGD, and cocoa, but to be honest, i can't see where help to reduce the communication. thank you very much.

**Comment by martinjaggi** [comment]
Thanks for the question!
The trade-off between communication and computation is steered by `params.localIters` (which is called `H` in the paper). This number describes how many datapoints are processed, before a single vector is communicated (per round).

You can freely set this parameter to say 10x,100x,1000x or even 10000x, depending on the speed of communication on the hardware system you're running on. It is a good idea to chose it such that communication and computation are then balanced. Compared to the slower mini-batch methods, it therefore has a similar role as the mini-batch size.

See also our newer arXiv paper, which describes this in more details: [https://arxiv.org/pdf/1611.02189](https://arxiv.org/pdf/1611.02189). And the newer code for L1 as well: [https://github.com/gingsmith/proxcocoa/](https://github.com/gingsmith/proxcocoa/)

**Comment by codlife** [comment]
oh,sorry , we can see in sgdf, there are also a params.localIters. what's the difference?

**Comment by martinjaggi** [comment]
There are many differences between CoCoA and SGD. We refer to the paper, slides, poster or presentation videos. One of the main differences is that CoCoA allows performing local updates before communication, while mini-batch SGD does not. Hope this helps a bit.

**Comment by codlife** [comment]
The below is the code in your cocoa imp, w just is updated one time after all executors(workers) are reduced, which is the same with your SGD imp, so i don't see what you mean.
 `

```
  val updates = zipData.mapPartitions(partitionUpdate(_, w, params.localIters, params.lambda, params.n, scaling, debug.seed + t, plus, parts * params.gamma), preservesPartitioning = true).persist()
  alpha = updates.map(kv => kv._2)

  val primalUpdates = updates.map(kv => kv._1).reduce(_ + _)
  w += (primalUpdates * scaling)
```

`

**Comment by 201520815029009** [comment]
I also saw your source code of this project, and I found that in cocoa.scala it needed return iteration( deltaw) of subroutine which was same to the sdg.scala return iteration(deltaw). where is the decreasion of communication?

**Comment by martinjaggi** [comment]
See above comment also. Indeed per round, communication of both methods is one vector (the size of the model). However, the vector will be very different, when using mini-batch SGD as when using CoCoA. We therefore implement both methods to allow a fair comparison.

**Comment by codlife** [comment]
than you very much ,got it.
