### ISSUE TITLE
More efficient imp

### ISSUE THREAD

**Issue by codlife** [gingsmith/cocoa#2]
Hi @gingsmith ：
I see you just use a global variable w, and then each worker access this variable directly, this imp is low-efficient, maybe  you can use spark broadcast. Maybe you can have a look about spark mllib min-batch SGD. Or them make no difference  in your experiment?

**Comment by gingsmith** [comment]
Hi @codlife, thanks for your comment -- yes, you are correct that we could use broadcast variables here, however this has not made an impact for us in practice.
