### ISSUE TITLE
Question about the experiment

### ISSUE THREAD

**Issue by codlife** [gingsmith/cocoa#3]
Hi @gingsmith @martinjaggi 
 I appreciate your work very much,According to my experiment on rcv1,
I get the result as below:
Cocoa:
Iteration:10
primal objective: 0.8666057156567569
primal-dual gap: 0.2516054343038072
test error: 0.07617222123736926
Iteration:20
primal objective: 0.838100858936967
primal-dual gap: 0.02272951383680888
test error: 0.07480573775335342
Iteration:30
primal objective: 0.8318824253272175
primal-dual gap: -0.05122631395372568
test error: 0.07369039177450806

Mini-batch SGD
Iteration: 780
primal objective: 0.8070251747438447
test error: 0.0726969213496425
Iteration: 790
primal objective: 0.8070243973940799
test error: 0.0726747621580098
Iteration: 800
primal objective: 0.8070240250300628
test error: 0.07265629616498256

Can you have a explanation about the experiment? why the mini-batch sgd primal objective is smaller then cocoa primal objective? and the stop condition. thank you very much.
   Best wishes!

**Comment by martinjaggi** [comment]
well you have only run 30 iterations of cocoa, vs 800 iterations of mini-batch SGD. a good comparison metric is the number of data examples processed in total (see the H parameter in cocoa and the mini-batch size in SGD).

**Comment by codlife** [comment]
@martinjaggi @gingsmith Yes ,I try to run cocoa according to your paper's best setting on rcv1
such as H = 1e5 in cocoa and mini-batch size = 100 in spark mini-batch size
but I get the result as below:

sgd
Iteration: 960
primal objective: 0.8070113758495256
test error: 0.07278555811617325
Iteration: 970
primal objective: 0.8070110315907472
test error: 0.07276339892454056
Iteration: 980
primal objective: 0.8070109717250984
test error: 0.07272646693848608
Iteration: 990
primal objective: 0.8070099592534166
test error: 0.0727043077468534
Iteration: 1000
primal objective: 0.8070093028479007
test error: 0.0727116941440643

cocoa 
Iteration:70
primal objective: 0.829177304889658
primal-dual gap: -0.0896790769289536
test error: 0.07305146841576553
Iteration:80
primal objective: 0.8291523684650991
primal-dual gap: -0.0900653905141966
test error: 0.07304038881994918
Iteration:90
primal objective: 0.8291436475764966
primal-dual gap: -0.09020156720869965
test error: 0.07303669562134374
Iteration:100
primal objective: 0.8291405487455461
primal-dual gap: -0.09024967105925663
test error: 0.07304038881994918

we can see the in cocoa the primal objective is always larger than that of spark mini-batch sgd even I run more iterations in cocoa. That's what trouble me? thank you!

**Comment by gingsmith** [comment]
Hi @codlife, 

What do the first 100 iterations of mini-batch SGD look like? You are comparing 1000 iterations of SGD to only 100 iterations of cocoa. Also, how are you setting the number of partitions (numSplits) and the regularization parameter (lambda)?

**Comment by codlife** [comment]
Hi @gingsmith 
I just run this experiment according to your paper(Communication-Efficient Distributed Dual Coordinate Ascent) best setting, I just set 
 H = 1e5 in cocoa , 
 mini-batch size = 100 ,
 lambda = 0.01,
 data partition = 10(this test data is about 1.2G) with 8 machine and 16 executors
But what make me confused is mini-batch sgd's primal objective value is always larger than cocoa,So interesting! than you @gingsmith very much.
the below is the experiment result. 
Iteration: 10
primal objective: 0.8134290628294657
test error: 0.07226112391419962
Iteration: 20
primal objective: 0.8097086490363239
test error: 0.07190288364947113
Iteration: 30
primal objective: 0.8087968952647187
test error: 0.07301453642971105
Iteration: 40
primal objective: 0.8083824943506535
test error: 0.07571795780889913
Iteration: 50
primal objective: 0.8080535205638826
test error: 0.07448442947467943
Iteration: 60
primal objective: 0.8079189212990748
test error: 0.07462477102168646
Iteration: 70
primal objective: 0.8077392882242245
test error: 0.07476880576729894
Iteration: 80
primal objective: 0.8076452181221789
test error: 0.07473926017845536
Iteration: 90
primal objective: 0.8075663813212794
test error: 0.07386397210896413
Iteration: 100
primal objective: 0.8075009211152085
test error: 0.07385658571175324

**Comment by codlife** [comment]
hello,@gingsmith please check this problem ,thank you very much!
 best wishes!

**Comment by gingsmith** [comment]
Hi @codlife, my apologies for the delay over the holidays. In the experiment you're referring to, we set lambda=1e-6 (this is a harder problem to solve), and we set the number of partitions to be 8. Also, note that we use the 'rcv1_test.binary' (from [LIBSVM](https://www.csie.ntu.edu.tw/~cjlin/libsvmtools/datasets/binary.html#rcv1.binary)) for training, and 'rcv1_train.binary' for testing.
